image: docker:20.10.24

pipelines:
  default:
    - step:
        name: Build and Push Frontend Docker Image
        services:
          - docker
        script:
          - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          - docker build -t mydockerhub/frontend:latest .
          - docker push mydockerhub/frontend:latest

    - step:
        name: Deploy to Kubernetes
        script:
          - apk add --no-cache kubectl
          - kubectl apply -f k8s/