apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: akeso-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 80   # Container port
  type: NodePort       # Change to LoadBalancer if using cloud
